using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpawnCreator.Definitions
{
    enum ConditionSourceType
    {
        CONDITION_SOURCE_TYPE_NONE = 0,
        CONDITION_SOURCE_TYPE_CREATURE_LOOT_TEMPLATE = 1,
        CONDITION_SOURCE_TYPE_DISENCHANT_LOOT_TEMPLATE = 2,
        CONDITION_SOURCE_TYPE_FISHING_LOOT_TEMPLATE = 3,
        CONDITION_SOURCE_TYPE_GAMEOBJECT_LOOT_TEMPLATE = 4,
        CONDITION_SOURCE_TYPE_ITEM_LOOT_TEMPLATE = 5,
        CONDITION_SOURCE_TYPE_MAIL_LOOT_TEMPLATE = 6,
        CONDITION_SOURCE_TYPE_MILLING_LOOT_TEMPLATE = 7,
        CONDITION_SOURCE_TYPE_PICKPOCKETING_LOOT_TEMPLATE = 8,
        CONDITION_SOURCE_TYPE_PROSPECTING_LOOT_TEMPLATE = 9,
        CONDITION_SOURCE_TYPE_REFERENCE_LOOT_TEMPLATE = 10,
        CONDITION_SOURCE_TYPE_SKINNING_LOOT_TEMPLATE = 11,
        CONDITION_SOURCE_TYPE_SPELL_LOOT_TEMPLATE = 12,
        CONDITION_SOURCE_TYPE_SPELL_IMPLICIT_TARGET = 13,
        CONDITION_SOURCE_TYPE_GOSSIP_MENU = 14,
        CONDITION_SOURCE_TYPE_GOSSIP_MENU_OPTION = 15,
        CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE = 16,
        CONDITION_SOURCE_TYPE_SPELL = 17,
        CONDITION_SOURCE_TYPE_SPELL_CLICK_EVENT = 18,
        CONDITION_SOURCE_TYPE_QUEST_ACCEPT = 19,
        CONDITION_SOURCE_TYPE_QUEST_SHOW_MARK = 20,
        CONDITION_SOURCE_TYPE_VEHICLE_SPELL = 21,
        CONDITION_SOURCE_TYPE_SMART_EVENT = 22,
        CONDITION_SOURCE_TYPE_NPC_VENDOR = 23,
        CONDITION_SOURCE_TYPE_SPELL_PROC = 24,
        CONDITION_SOURCE_TYPE_TERRAIN_SWAP = 25,
        CONDITION_SOURCE_TYPE_PHASE = 26,
        CONDITION_SOURCE_TYPE_MAX = 27  // MAX
    }
}
